name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix: 
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
#     - name: Run tests
#       run: cargo test --verbose
    - name: Rename
      run: mv target/release/hxdown target/release/hxdown-${{ matrix.os }}
    - name: Release & Assets
      # You may pin to the exact commit or the version.
      # uses: Hs1r1us/Release-AIO@354b8db50d5b6310b621cb6c5e29d1f8e611aff7
      uses: Hs1r1us/Release-AIO@v1.0
      with:
        # The name of the tag
        tag_name: develop
        # The name of the release
        release_name: Latest Developing Version
        asset_files: target/release/hxdown-${{ matrix.os }}
        prerelease: true

